configuration_id: 1
tolerated_byzantine_faults: 1
tolerated_unavailable_replicas: 0
service_keys: {}
sites:
- name: control_center1
  type: CONTROL_CENTER
  hosts:
  - name: goldenrod1
    ip: 192.168.0.101
    permanent_key_location: tpm_keys/goldenrod1_tpm_private.pem
    permanent_public_key: '-----BEGIN PUBLIC KEY-----

      MIIBojANBgkqhkiG9w0BAQEFAAOCAY8AMIIBigKCAYEAm734+MkD2K1mlOAjSYhf

      EOcT5LPu5Az0+cP3nV4PL1ITevT2dKwqpeYJs8g6tKDikKz51JXqVyDwikoiSuGY

      z0GWns19tzcbuB4S36NwpRhf7qdfR0SwznJAbvUmyumk5KBAgD7U09H1G2YU107J

      3+Rq6JaFhCnJaSCyDpoCS/tvpFyfh3Lattfl7eoDUOjtcG46Yj10MQ7eTRK0cDCp

      cvGKmJjDjRmdIvLewRP/qgchhpG0LtuhYd1TdgYz35ffEi7/cvJppFGKbvlaoWsG

      TYkcODUAFko6nNQQx3JNLz1wLTScL3wI5b+RjPN6Nb1sLWwD6xUtICKT+BWwMAe7

      qhCc5rv4dYKghyiBVbNdSOfEWleW0gZy8pZdHZnZpqpA9vhN5iHJQG1RB2FSJl2h

      15o+Ffw8k9H2g0v/aKYQO9UxHndV15ip9/cP1V3ANqGSfGdS3UkWxrw/eZGeHDFD

      nyrL0fE2vS4xbnqAQoREqf0UFFYhT8zLtpEUUeGqVPy/AgMBAAE=

      -----END PUBLIC KEY-----

      '
    runs_spines_internal: 1
    runs_spines_external: 1
  - name: goldenrod2
    ip: 192.168.0.102
    permanent_key_location: tpm_keys/goldenrod2_tpm_private.pem
    permanent_public_key: '-----BEGIN PUBLIC KEY-----

      MIIBojANBgkqhkiG9w0BAQEFAAOCAY8AMIIBigKCAYEAu5Z3l4fiqtSlAttQP6m2

      FJyy7/chNhoH5jRlzJ/0oHB35ibfbUztTvdPgqt7A07+t862Z4XFdBjX/DWium5s

      UaWJzUsr1/u6VDXOYSiFOctXVQKXobY5so+MwvhUW4km6LqZfIr5P+DaJebiQrQt

      3AzKuDykddmxcTHM4iTiuElgA61XAf7jPNXwysF4FKqCrVp87fAKpHZkRHNoQoU0

      Kx7mOlWqGqW8f5ndviv2xwP38Kxn+cn1hzb6Vf9fP/YywdU+QOZX9EduYjGimd45

      zNOktTM5BTrd8wo30FKYkSFTsPjz0PaFjwQPVZAc3JASTHQcHlMGQZMkUNZYE34v

      qROcKHxUg1r7VyMNhnmqxdJhWGZeZ8n99/4lu1tiIXorzeiLS4jzQbGjvxFQAZDo

      QjuJEtLV/XLVHrUNQIfaiqFrRqRbu7fxoUC42aqmXFKRZQQ6ANC9L+vIPgs8TtcD

      t8OLKMH3+W4qUoE8Qa4Dlk51EonX7t+OenfR9tHsI9hHAgMBAAE=

      -----END PUBLIC KEY-----

      '
    runs_spines_internal: 1
    runs_spines_external: 1
  - name: goldenrod3
    ip: 192.168.0.103
    permanent_key_location: tpm_keys/goldenrod3_tpm_private.pem
    permanent_public_key: '-----BEGIN PUBLIC KEY-----

      MIIBojANBgkqhkiG9w0BAQEFAAOCAY8AMIIBigKCAYEAwGxdODrgSa6zYGNFzns9

      KgehtWqDT9Vtq0HvDIUHKHAzTFcPkKKJemwKH0DlkMRViMbYqE/MyR/PgGE7V1s7

      ewNS3VkS4Q654Ev3fVnR1nT2h/0mqfknQIdTKuWCBW9StZw7koezTMJrZTuQLvep

      AtrcC04GT8vxUlx01MMQ8wBkslvtZicNKe64zwqMziIZYwqZ2qt1Fap2lvXc/FwF

      u2da5jkS4PknKVSD+m92ga12B94fHLU74OHUP3k5fonZvk+BbMlQZhUazS+fb60b

      CkPu8zKq5Y1IPERLDY+QJV9eD3jj5/KIC6pR91zNlQUyiZuH2PDMLByS5fp/TynN

      zbUfSyIWI+moPlTiCq/lHrGFMWNx4+sLjnPLL2g/3YEel8FeX8JchNV9KbfmH4Ep

      wHK1zOF4Kajr2jiMHT43tF43Awp2hpfivLG42XwegIpIW9yEpx4LETRNnBFe8Wq2

      j/W20tO9bXofMB0T9hBUYgO5D3d5ah6e1V+IHik/I79BAgMBAAE=

      -----END PUBLIC KEY-----

      '
    runs_spines_internal: 1
    runs_spines_external: 1
  - name: goldenrod4
    ip: 192.168.0.104
    permanent_key_location: tpm_keys/goldenrod4_tpm_private.pem
    permanent_public_key: '-----BEGIN PUBLIC KEY-----

      MIIBojANBgkqhkiG9w0BAQEFAAOCAY8AMIIBigKCAYEAqtsNkOorp7FqPpaT6waW

      Vb9PmYPB7W1JAc1rCwPBTZL3x3YrC/ey07OZT0dZLFKEqj8VlDDU8HmJAfaRluK6

      vxLBy+1ls2GALNMKkcb40l+OYk+WQRa0ksSJxL8kmo7ATlf7hd44HRd/ZJnP8dXo

      VlEgMr6MwK8x+2qrRjKRBpLe0VyBgWIvPV1wrIRrjJVuH+mYHWD6c4l8UcalM8cq

      Dzco3tUWsE/Bml/1xBgiQbKQjG9xNlH5aWdTk5jhht+v6talS4NyT2asGsmc6OeO

      IHXqyNYxlhqNQubg2cTNd78UIzFlQiN7tAW2umMJzWg565F2M3kqyea3VK4Oh6QT

      b7Fi5Jn3ix67VkMgGYqmrqONyTUo2z/317fRSDULNTx8phoRi5CHMES2dzO38Q9M

      HZ7lMGXY74olxBWwCnPHvIhx5QT11XU70oejGTQTkreU/AtROY7O04Y+31AUIWHB

      yU2SMUtEcGstJNXTdmcgyrBKsWw7GiNEQersMUCt7tAbAgMBAAE=

      -----END PUBLIC KEY-----

      '
    runs_spines_internal: 1
    runs_spines_external: 1
  replicas:
  - instance_id: 1
    host: goldenrod1
    spines_internal_daemon: goldenrod1
    spines_external_daemon: goldenrod1
  - instance_id: 2
    host: goldenrod2
    spines_internal_daemon: goldenrod2
    spines_external_daemon: goldenrod2
  - instance_id: 3
    host: goldenrod3
    spines_internal_daemon: goldenrod3
    spines_external_daemon: goldenrod3
  - instance_id: 4
    host: goldenrod4
    spines_internal_daemon: goldenrod4
    spines_external_daemon: goldenrod4
- name: plc_site
  type: CLIENT
  hosts:
  - name: goldenrod5
    ip: 192.168.0.105
    permanent_key_location: tpm_keys/goldenrod5_tpm_private.pem
    permanent_public_key: '-----BEGIN PUBLIC KEY-----

      MIIBojANBgkqhkiG9w0BAQEFAAOCAY8AMIIBigKCAYEAn9kZoV64/p9L35ms8JUa

      i2dhlTmV7g0nE2SeqdrINwOUpV9aOag1eCO2V2fnLJ4EF20/nXA3EtH9kC0sR+nD

      3YgDsZWO7bBVU4m6SHGssz+4hGWczhozBn78Hg0+FNKPElJI3Ujc5GAFdNUusClZ

      ThPBTLggroINyuN0VqNoiZcikxBHQm+uHTBawej17ungBVbhDAUeybWwM9ypKAY4

      zsgRRnYTgJ/hQF48ctqXu6nT9f8azAOiJqfvvu/xHtwUJpqD7tzBM1Vc3y77ehtF

      v8hiwLldNXFrydxxO17CbAJMxNoz1Ixo4q+GG43HwHHaB7Evk9GAMrFr81iPSXln

      SQ8SHoiioxn8SDk5+2QQC0FQrUkQNpjw+kLglG/ss7IcuhsoakwTRzZK+59o8Q0W

      Mxe3cCJAwo5isub862utDsQcZ8joaMitmqXUP1DTPbqoF85Dj+JFPXAVGj5r7J45

      nMdu6Vudg8qJXEbhxohk2iEno7el6P3t+IMm5fUB0SJJAgMBAAE=

      -----END PUBLIC KEY-----

      '
    runs_spines_internal: 0
    runs_spines_external: 1
  clients:
  - client_id: 1
    host: goldenrod5
    spines_external_daemon: goldenrod5
    type: benchmark
