configuration_id: 1
tolerated_byzantine_faults: 1
tolerated_unavailable_replicas: 1

sites:
  - name: control_center1
    type: CONTROL_CENTER
    hosts:
      - name: cc1_host1
        ip: 1.1.1.1
        permanent_key_location: "prime/bin/tpm_keys/tpm_private1.key"
        runs_spines_internal: 1
        runs_spines_external: 1
      - name: cc1_host2
        ip: 1.1.1.2
        runs_spines_internal: 0
        runs_spines_external: 0
      - name: cc1_host3
        ip: 1.1.1.3
        runs_spines_internal: 0
        runs_spines_external: 0
      - name: cc1_host4
        ip: 1.1.1.4
        runs_spines_internal: 0
        runs_spines_external: 0
      - name: cc1_host5
        ip: 1.1.1.5
        runs_spines_internal: 0
        runs_spines_external: 0
      - name: cc1_host6
        ip: 1.1.1.6
        runs_spines_internal: 0
        runs_spines_external: 0
    replicas:
      - instance_id: 1
        host: cc1_host1
        spines_internal_daemon: cc1_host1
        spines_external_daemon: cc1_host1
      - instance_id: 4
        host: cc1_host2
        spines_internal_daemon: cc1_host1
        spines_external_daemon: cc1_host1
      - instance_id: 7
        host: cc1_host3
        spines_internal_daemon: cc1_host1
        spines_external_daemon: cc1_host1
      - instance_id: 10
        host: cc1_host4
        spines_internal_daemon: cc1_host1
        spines_external_daemon: cc1_host1
      - instance_id: 13
        host: cc1_host5
        spines_internal_daemon: cc1_host1
        spines_external_daemon: cc1_host1
      - instance_id: 16
        host: cc1_host6
        spines_internal_daemon: cc1_host1
        spines_external_daemon: cc1_host1

  - name: control_center2
    type: CONTROL_CENTER
    hosts:
      - name: cc2_host1
        ip: 2.2.2.1
        permanent_key_location: "prime/bin/tpm_keys/tpm_private2.key"
        runs_spines_internal: 1
        runs_spines_external: 1
      - name: cc2_host2
        ip: 2.2.2.2
        runs_spines_internal: 0
        runs_spines_external: 0
      - name: cc2_host3
        ip: 2.2.2.3
        runs_spines_internal: 0
        runs_spines_external: 0
      - name: cc2_host4
        ip: 2.2.2.4
        runs_spines_internal: 0
        runs_spines_external: 0
      - name: cc2_host5
        ip: 2.2.2.5
        runs_spines_internal: 0
        runs_spines_external: 0
      - name: cc2_host6
        ip: 2.2.2.6
        runs_spines_internal: 0
        runs_spines_external: 0
    replicas:
      - instance_id: 2
        host: cc2_host1
        spines_internal_daemon: cc2_host1
        spines_external_daemon: cc2_host1
      - instance_id: 5
        host: cc2_host2
        spines_internal_daemon: cc2_host1
        spines_external_daemon: cc2_host1
      - instance_id: 8
        host: cc2_host3
        spines_internal_daemon: cc2_host1
        spines_external_daemon: cc2_host1
      - instance_id: 11
        host: cc2_host4
        spines_internal_daemon: cc2_host1
        spines_external_daemon: cc2_host1
      - instance_id: 14
        host: cc2_host5
        spines_internal_daemon: cc2_host1
        spines_external_daemon: cc2_host1
      - instance_id: 17
        host: cc2_host6
        spines_internal_daemon: cc2_host1
        spines_external_daemon: cc2_host1

  - name: data_center
    type: DATA_CENTER
    hosts:
      - name: dc_host1
        ip: 3.3.3.1
        permanent_key_location: "prime/bin/tpm_keys/tpm_private3.key"
        runs_spines_internal: 1
        runs_spines_external: 1
      - name: dc_host2
        ip: 3.3.3.2
        runs_spines_internal: 0
        runs_spines_external: 0
      - name: dc_host3
        ip: 3.3.3.3
        runs_spines_internal: 0
        runs_spines_external: 0
      - name: dc_host4
        ip: 3.3.3.4
        runs_spines_internal: 0
        runs_spines_external: 0
      - name: dc_host5
        ip: 3.3.3.5
        runs_spines_internal: 0
        runs_spines_external: 0
      - name: dc_host6
        ip: 3.3.3.6
        runs_spines_internal: 0
        runs_spines_external: 0
    replicas:
      - instance_id: 3
        host: dc_host1
        spines_internal_daemon: dc_host1
        spines_external_daemon: dc_host1
      - instance_id: 6
        host: dc_host2
        spines_internal_daemon: dc_host1
        spines_external_daemon: dc_host1
      - instance_id: 9
        host: dc_host3
        spines_internal_daemon: dc_host1
        spines_external_daemon: dc_host1
      - instance_id: 12
        host: dc_host4
        spines_internal_daemon: dc_host1
        spines_external_daemon: dc_host1
      - instance_id: 15
        host: dc_host5
        spines_internal_daemon: dc_host1
        spines_external_daemon: dc_host1
      - instance_id: 18
        host: dc_host6
        spines_internal_daemon: dc_host1
        spines_external_daemon: dc_host1

  - name: plc_site
    type: CLIENT
    hosts:
      - name: plc
        ip: 5.5.5.5
        runs_spines_external: 1
        runs_spines_internal: 0

  - name: hmi_site
    type: CLIENT
    hosts:
      - name: hmi
        ip: 6.6.6.6
        runs_spines_external: 1
        runs_spines_internal: 0
