configuration_id: 1
tolerated_byzantine_faults: 1
tolerated_unavailable_replicas: 1
service_keys: {}
sites:
- name: control_center1
  type: CONTROL_CENTER
  hosts:
  - name: goldenrod1
    ip: 192.168.0.101
    permanent_key_location: tpm_keys/goldenrod1_tpm_private.pem
    permanent_public_key: '-----BEGIN PUBLIC KEY-----

      MIIBojANBgkqhkiG9w0BAQEFAAOCAY8AMIIBigKCAYEAu7kAuX5JFtqOaj2yQhst

      L2Bz+rpABWZ9X+DbXjP5cEvTPbA0iI5q3M2Q68V7VDcU0p5CqP8CzaUF/3INpH1V

      r2C4ob5KLThIgJDirs78wsfmDioFh2EkonNUniv+mIASSRz7zXEZT4p+Yni7bYku

      ZmAJhzBbK/HKOjOJWdn7j618hsvf5A8f7/xgaMWPVZ9QRB3zSJVgwwrznSrRp07j

      Te2JXMJgMfbSrr6s1XW5IeeMt+D6Z4yYLTI2x4Xj/1F40umaZBydt7RNVT0puOnx

      6W0osySenCFAyHaZLDtQMYD4H5BmxmhRs9qHbnjJGxQF6AgpW9W+MqRr+gHSQ3S/

      HusESD/kGOEOB25jOZHUox+9utoOMdRI/h2o0xvw6TlLF6sakRpmEW/VBullHUdb

      G1LqyIZ2B3Y6VH/hah3HAaBDyQ9vCAAygIVQIAYPp5z2MqKnksLUO1xdei0PTeQm

      5z9MuGU5kCR9vQauSyNqQIzif+yTOgmbXpJdGwzBrddxAgMBAAE=

      -----END PUBLIC KEY-----

      '
    runs_spines_internal: 1
    runs_spines_external: 1
  - name: goldenrod2
    ip: 192.168.0.102
    permanent_key_location: tpm_keys/goldenrod2_tpm_private.pem
    permanent_public_key: '-----BEGIN PUBLIC KEY-----

      MIIBojANBgkqhkiG9w0BAQEFAAOCAY8AMIIBigKCAYEAtP1Yggp7AwAAyLTx9TTl

      Z+U/E9hotNXPgFkHmy4eftjio/871o1Rnq7WC8xoty/xB3J/aMYXBC/r5kdxKZt4

      f/acw8XpIb371YToMiF1flgu6aMjJazl5o+yn4T1X3xVakuFnYHBU0DJEOnQIdW/

      30jx+IxqXgZFK6L+yyLmiJt0zxUKtgqYt3JGZiNgkipBl54+0ln/DViLT1gvHSMv

      HouaFmdzu3pUyORGTbbi37biD6VSJD3TQpeA7HplljvAq3HjfsW9JCdVpAWTnt1E

      OGmMusQGBPONRVP+6CJBROZ4WjrFI5n/pjNnr/PFH2nNyF18sMAHYRLpiwwI3lsb

      m18/lg8epnOlU/HtfMlKkJNk04J9viWm1xSKAeaZaiIM2Scbkz8iF0buQcyIPBSS

      MSor92g71ZvhvPN88sPU1cJzeiDb9uLFNXBLzteVq6y5XO3vXSB1iF0Kh/q2kF0k

      V192Y4Cios0fw3Uo5Nz74ap3LdNYAWKrxDIxCoMigMK/AgMBAAE=

      -----END PUBLIC KEY-----

      '
    runs_spines_internal: 1
    runs_spines_external: 1
  - name: goldenrod3
    ip: 192.168.0.103
    permanent_key_location: tpm_keys/goldenrod3_tpm_private.pem
    permanent_public_key: '-----BEGIN PUBLIC KEY-----

      MIIBojANBgkqhkiG9w0BAQEFAAOCAY8AMIIBigKCAYEA0UxcENEO1ZUBjKfl/rJp

      zvR0EGTdvUfRQ3P2Tf3JRwMfQFef2U6kKetAVWtlQKEjOfHiX6e/nzywUHJWkDa3

      FbV2ng/Mxa+sSIh2Z1AUzDQrpdh7leTs0Q0fH1JEUR1+b5RQ+uvLF8+vByqrvHDq

      4PfW5IWaK/H3LP1+CfQntmfvo4w0L51iCgVEzH7melh8xSHNvQ7FDsEJH2y0QR7p

      dCA6AsDU1LX4Bad+nccG9rp7F4uYhkxn7zPx16cAVKK74kX6WBToqlJ0ZvfX478V

      CA1Ozz+7stCf42Ra+mtSAXEKi0ZvCM44MnIuRCCG58rLDKVYhYX0HeSespH2aIoy

      cJi7OG+GlrEiqD8ZZlIoMSSWJy9IuPBWuUPjnutf0V8DwHfXCFiJ8Hk0IQBoK6rU

      39/Pjr5Mp8jVTK8vK2fSMLRR5kEi8xFJ8rC9lNoTq++G0lcviQAFdjz+FSwmVKAy

      wjVGtAnV+Mz8NFEXUdlsGoxT0MqT+F3+K9Qlc/7jJ7DFAgMBAAE=

      -----END PUBLIC KEY-----

      '
    runs_spines_internal: 1
    runs_spines_external: 1
  - name: goldenrod4
    ip: 192.168.0.104
    permanent_key_location: tpm_keys/goldenrod4_tpm_private.pem
    permanent_public_key: '-----BEGIN PUBLIC KEY-----

      MIIBojANBgkqhkiG9w0BAQEFAAOCAY8AMIIBigKCAYEAmFZlVVAGZIza2f+3JPQ+

      K4F+bGO2Hd7RBzujb3XrtlyyObSOg00/7VjH4heSHG94mUe3mkwgR06pLo8p06TD

      CkNk8lLukcB8KShNHoTw+p6Cg/WjCptSYEE/CaYHmLg6K9kbpOup+NUobLgAinxs

      sc0Xb4H86UiBDr420372R6elEOTHjLweOV+jr5mmbhHp19BJk/33+V49VCkeMpk3

      5JIbjshQ3HWQAWDOkaW32KdO/a/IB/3sKNawsvOUG8BnpTn7NiAzACs4ve6zEPtE

      uOJxt2R/aC+nrVwH3D2NGkGGtjNBMlXKK+uuRYqV6nDdT9maL5XRHVSlLgQzksSH

      uPzs7syHevSw1UUyLLv6FhhLGiEN/IfHw2luTWO/nOPYbe6M/71+YQcVNB/RW1MY

      kJ/oCWG8aOV/811VnA+PFEpfHSP0PI5dLhFdPFHAft623h9WjibBNIz1eXgA0K+d

      niwB0V7GZgq9fgzM5DwhUrESyYhcB+COegK+zghQ+oA5AgMBAAE=

      -----END PUBLIC KEY-----

      '
    runs_spines_internal: 1
    runs_spines_external: 1
  - name: goldenrod7
    ip: 192.168.0.107
    permanent_key_location: tpm_keys/goldenrod7_tpm_private.pem
    permanent_public_key: '-----BEGIN PUBLIC KEY-----

      MIIBojANBgkqhkiG9w0BAQEFAAOCAY8AMIIBigKCAYEA/u3TPM3XmxnZICfKNMPg

      rRnweG3msEMa9jW8uB8R5rbrV3/r+EFf5cKWXgTtpQGIfNYjmRU7KuAb+lhZUGwp

      m9E7VUubrJLHhqCG5rJPOFC+3xhowP+TFlCJ2koSC/eAy+vkoJsqTQEGhbjadIrw

      6wmuBj+C4EDklqI/7/TrroCtC4iPfptgwPj0VbI16JSdmQRvGII8VnmxJ9ylpn8G

      PIMq4xSRfh8hwI9wHZNsJoDKIha6N7Xy5IIY/cOsyV/k1LVypjBvmSYRLMacUcy8

      gj7PBjohGSwjG84ku7Pu5fhPdV0UOdcVCut0wWgUnSao3JthEOLjsKPYQaqw63Ap

      cdKbaXhVCAe0L9gN5DZqbmiCrecTqpO7bKUi6CpS4XZQBTygAd+W5wRFfklE8t5o

      kTPowEfSuYSuOuWJ9rX74A7+Bu6yy5/WYuINSr4ilyxpbA0uE8OGPCuaUh+B58cc

      HsJTiAnJs148Zg+jv0HI59H0illRCAO0/JnPb+WJ5oG3AgMBAAE=

      -----END PUBLIC KEY-----

      '
    runs_spines_internal: 1
    runs_spines_external: 1
  - name: goldenrod8
    ip: 192.168.0.108
    permanent_key_location: tpm_keys/goldenrod8_tpm_private.pem
    permanent_public_key: '-----BEGIN PUBLIC KEY-----

      MIIBojANBgkqhkiG9w0BAQEFAAOCAY8AMIIBigKCAYEA0yVL88YmJ13a24qKslYr

      FvOPFNUi+ptS25o0iqfFbYr08Veq9VqJ2z5ZyhRVTb+E1i2cZy53SYuvTzVYYkhX

      SIDajh5q3vPIokfoQKeSNcWU4/KW9VzJX91hmK/TfBiZ2/MWvqDmdC8lokWu0R0v

      9TDa2sHsnAUu+/ohZRcp0kuh4APU4xePpHDGVyqpJAf2spslKJ9QwsCBmXkFIsm9

      gv1YIR9h9zmWJGXqTOh2B/chZ8WYxJgI2B2dtslLUMOyh0KHvLXLLFTT/Dgk3EIb

      OYq+EYKnkX8RoWguKjIGvcB7JoCVC3cts3+E71Zno1ktjZ/7CfieKrS2ZMJq3WAj

      Yju1j4csYYyn407Lj4HGfKhsI4oK7uUMVLvpU00ww9r0y/ahdJI64zHs+ftrJkLm

      2t5Ak/ekI7i3/bJ3G3OSTqATkZlzhNJEsN7+BuKQ2twH5pLJ5SCMz4IYcJ8L6x69

      yRQnaJlAj8NAGFUaN9P/6Iki5l+zUTLWp3PkAGLlJXXLAgMBAAE=

      -----END PUBLIC KEY-----

      '
    runs_spines_internal: 1
    runs_spines_external: 1
  replicas:
  - instance_id: 1
    host: goldenrod1
    spines_internal_daemon: goldenrod1
    spines_external_daemon: goldenrod1
  - instance_id: 2
    host: goldenrod2
    spines_internal_daemon: goldenrod2
    spines_external_daemon: goldenrod2
  - instance_id: 3
    host: goldenrod3
    spines_internal_daemon: goldenrod3
    spines_external_daemon: goldenrod3
  - instance_id: 4
    host: goldenrod4
    spines_internal_daemon: goldenrod4
    spines_external_daemon: goldenrod4
  - instance_id: 5
    host: goldenrod7
    spines_internal_daemon: goldenrod7
    spines_external_daemon: goldenrod7
  - instance_id: 6
    host: goldenrod8
    spines_internal_daemon: goldenrod8
    spines_external_daemon: goldenrod8
- name: plc_site
  type: CLIENT
  hosts:
  - name: goldenrod5
    ip: 192.168.0.105
    permanent_key_location: tpm_keys/goldenrod5_tpm_private.pem
    permanent_public_key: '-----BEGIN PUBLIC KEY-----

      MIIBojANBgkqhkiG9w0BAQEFAAOCAY8AMIIBigKCAYEAmIMeoRz3TlRtABocm0vw

      TWqs5CJcbmheiTU+0wxYxcf5kiOM1vX0SPCtrwkpr0OpAcZNaylQ5FC13Pt6YeHX

      vMgWFypYAQQh1h+k8XuTvxOlcPNjHcTgANtAe9Ms42/speJEMSYl5RdEhXol2+UU

      7fLoVjpQlnG0GAO/IZXUrnf5AhCwDzIsLk5RtHFB6kPB/ia9VlpuzrPqYlwS3eY4

      wsXbHgdlz83fL7mPHiZAtO6HiuN3Oz01bYoKbXXVG7dzDgqgLXZwJzMjbwjnmw2+

      YMfx9z9ybpfVaj2FLX+kY5WI6oxbV8xnGO1198NVRRC1xui5pMlFkzJ3zUYen663

      nuoUWcxXFIQLW3MGAhCkOxTPnuroGKUysVf2rI9gPGXTW2841MqupYC62dN265kf

      8aQ/wJAo9xEwf32Kmgi8yF2hofKCrnuZ/o7xhN/Z+I31AMFkarngC1GKHzPGeaJF

      YGxmlXYgPPX/fZYZyd12PoqAEXoVEdFJUzZjSMe4Vg1JAgMBAAE=

      -----END PUBLIC KEY-----

      '
    runs_spines_internal: 0
    runs_spines_external: 1
  clients:
  - client_id: 1
    host: goldenrod5
    spines_external_daemon: goldenrod5
    type: benchmark
