configuration_id: 1
tolerated_byzantine_faults: 1
tolerated_unavailable_replicas: 0

sites:
  - name: control_center1
    type: CONTROL_CENTER
    hosts:
      - name: goldenrod1
        ip: 192.168.0.101
        permanent_key_location: "tpm_keys/goldenrod1_tpm_private.pem"
        runs_spines_internal: 1
        runs_spines_external: 1
      - name: goldenrod2
        ip: 192.168.0.102
        permanent_key_location: "tpm_keys/goldenrod2_tpm_private.pem"
        runs_spines_internal: 1
        runs_spines_external: 1
      - name: goldenrod3
        ip: 192.168.0.103
        permanent_key_location: "tpm_keys/goldenrod3_tpm_private.pem"
        runs_spines_internal: 1
        runs_spines_external: 1
      - name: goldenrod4
        ip: 192.168.0.104
        permanent_key_location: "tpm_keys/goldenrod4_tpm_private.pem"
        runs_spines_internal: 1
        runs_spines_external: 1

    replicas:
      - instance_id: 1
        host: goldenrod1
        spines_internal_daemon: goldenrod1
        spines_external_daemon: goldenrod1
      - instance_id: 2
        host: goldenrod2
        spines_internal_daemon: goldenrod2
        spines_external_daemon: goldenrod2
      - instance_id: 3
        host: goldenrod3
        spines_internal_daemon: goldenrod3
        spines_external_daemon: goldenrod3
      - instance_id: 4
        host: goldenrod4
        spines_internal_daemon: goldenrod4
        spines_external_daemon: goldenrod4

  - name: plc_site
    type: CLIENT
    hosts:
      - name: goldenrod5
        permanent_key_location: "tpm_keys/goldenrod10_tpm_private.pem"
        ip: 192.168.0.105
        runs_spines_external: 1

  - name: benchmark_site
    type: CLIENT
    hosts:
      - name: goldenrod6
        permanent_key_location: "tpm_keys/goldenrod11_tpm_private.pem"
        ip: 192.168.0.106
        runs_spines_external: 1
    clients:
      - client_id: 1
        host: goldenrod6
        spines_external_daemon: goldenrod6
        type: JHU #(hmis (JHU, PNNL, or EMS), proxy, benchmark)  
        # instance_public_key: XXXX
        # encrypted_instance_private_key: XXXX
        
